language: r
cache: packages

r:
  - oldrel
  - release
  - devel

env:
  global:
    - _R_CHECK_TESTS_NLINES_=0

r_github_packages:
    - jimhester/covr
    - jimhester/lintr
    - r-lib/pkgdown
    
script:
  - R CMD build .
  - R CMD check --as-cran *tar.gz

after_success:
  - R CMD INSTALL $PKG_TARBALL
  - Rscript -e 'lintr::lint_package()'
  - rm -rf qmongr.Rcheck
  - Rscript -e 'pkgdown::build_site()'
  - Rscript -e 'covr::codecov()'

deploy:
  # our site to gh_pages
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: false
    local_dir: docs
    on:
      branch: master
      condition: $TRAVIS_R_VERSION_STRING == "release"
